<select name="layered-nav-select" onChange="setLocation(this.value)">
    <option selected="selected" value="#">Please Select</option>
    <?php foreach ($this->getItems() as $_item): ?>                
            <?php if ($_item->getCount() > 0): ?>
                <option value="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                    <?php
                    echo $_item->getLabel();
                    if ($this->shouldDisplayProductCount()):
                        echo '(' . $_item->getCount() . ')';
                    endif; 
                    ?>
                </option>                
            <?php else: ?>
                <option value="#">
                    <?php
                    echo $_item->getLabel();
                    if ($this->shouldDisplayProductCount()):
                        echo '(' . $_item->getCount() . ')';
                    endif; 
                    ?>
                </option>
            <?php endif; ?>        
    <?php endforeach ?>
</select>