<!DOCTYPE html>

<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js"> <!--<![endif]-->

<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <div class="main-wrapper-lo">
            <div class="main-wrapper-in">
                <?php echo $this->getChildHtml('header') ?>
                <div class="main-container col1-layout">
                        <div class="col-main">
                            <?php echo $this->getChildHtml('global_messages') ?>
                            <?php
                            $category = Mage::getSingleton('catalog/layer')->getCurrentCategory();
                            $categories = $category->getCollection()
                                    ->addAttributeToSelect(array('name', 'thumbnail', 'image', 'description'))
                                    ->addAttributeToFilter('is_active', 1)
                                    ->addIdFilter($category->getChildren())
                            ?>
                            <div class="full-width collection--list">
                                
                                <?php foreach ($categories as $category): ?>
                                    <div class="half-width collection--item">
                                        <a href="<?php echo $category->getUrl() ?>">
                                            <img src="<?php echo Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . $category->getImage() ?>" alt="<?php echo $this->htmlEscape($category->getName()) ?>">
                                            <div class="caption">
                                                <div class="caption-inner">
                                                    <div class="caption-text">
                                                        <h2 class="heading3"><?php echo $this->htmlEscape($category->getName()) ?></h2>
                                                    </div>
                                                    <div class="button3">Shop Now</div>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>    
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>

