<!DOCTYPE html>

<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js"> <!--<![endif]-->

<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <div class="main-wrapper-lo">
            <div class="main-wrapper-in">

                <?php echo $this->getChildHtml('header') ?>
                <div class="main-container col1-layout">
                   
                    <div class="col-main">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        
                        <?php echo $this->getChildHtml('content') ?>

                    </div>
            </div>
        </div> 
        </div>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>

<script type="text/javascript">
/*
        jQuery(document).ready(function() {
            var feed = new Instafeed({
                get: 'user',
                userId: '262956837',
                accessToken: '50672391.6f8c5e0.85413253d0904b88a6125bddcfd115e3',
                target: 'ig',
                resolution: 'standard_resolution',
                limit: 1,
                template: '<img src="{{image}}" />'
            });

            feed.run();
     
       

         }); */
</script>
</body>
</html>

