<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Driver Template
 * @var $this Gene_BlueFoot_Block_Entity_PageBuilder_Block_Default
 *
 */
?>
<div class="gene-bluefoot-driver gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">
    <img src="/media/gene-bluefoot/{{ image }}" />
    <span class="gene-bluefoot-driver-title">{{ link_text }}</span>
</div>