<?php
/**
 *
 * @category    design
 * @package     grain_savageandrose
**/
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>


<header id="header" class="page-header">
    <div class="page-header-container">
        
     
        <div class="mobile-nav">
            <a href="#" class="mobile-nav-parent mobile-nav-parent__menu active">
                Menu
            </a>
            <a class="mobile-nav-parent mobile-nav-parent__account" href="#">
                Account 
            </a>

            <a href="#" class="close-menu">
                <i class="fa fa-close"></i>
            </a>

            
            <div class="mobile-nav-list mobile-nav-list__menu active">
                <?php echo $this->getChildHtml('topMenu') ?>
            </div>
            <div class="mobile-nav-list mobile-nav-list__account">
                <?php echo $this->getChildHtml('topLinks') ?>
            </div>
        </div>

        
        <a href="#" class="nav-toggle" aria-hidden="false"><i class="fa fa-navicon"></i></a>

        <a class="logo" href="<?php echo $this->getUrl('') ?>">
            Savage and Rose
        </a>

        <!-- Skip Links -->

        <div class="skip-links">
           
            <a href="#header-search" class="skip-link skip-search">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Search'); ?></span>
            </a>

            <div class="account-cart-wrapper">
                <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#header-account" class="skip-link skip-account">
                    <span class="icon"></span>
                    <span class="label"><?php echo $this->__('Account'); ?></span>
                </a>

                <!-- Cart -->

                <div class="header-minicart">
                    <?php echo $this->getChildHtml('minicart_head'); ?>
                </div>
            </div>


        </div>

        <!-- Navigation -->

        <div id="header-nav" class="skip-content">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>

        <!-- Search -->

        <div id="header-search" class="skip-content">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>

        <!-- Account -->

        <div id="header-account" class="skip-content">
            <?php echo $this->getChildHtml('topLinks') ?>
        </div>
    </div>
</header>

<div class="c-mask"></div><!-- /c-mask -->

<?php echo $this->getChildHtml('topContainer'); ?>
