<?php $category = Mage::getSingleton('catalog/layer')->getCurrentCategory(); ?>

<div class="full-width categoryheader">
    <img class="tablet categoryheader--image" src="<?php echo Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . $category->getThumbnail() ?>" alt="<?php echo $this->htmlEscape($category->getName()) ?>" />   
    <div class="categoryheader--caption">
	    <div class="categoryheader--captioninner">
	        <h1 class="categoryheader--title"><?php echo $this->htmlEscape($category->getName()) ?></h1>
	        <h2 class="categoryheader--description"><?php echo $this->htmlEscape($category->getDescription()) ?></h2>
	    </div>
    </div>      
</div>